POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxZDU3NDc1NzBkYWI2N2ExMjk4MWE3YyIsImlhdCI6MTY0MTM4ODE3MSwiZXhwIjoxNjQxMzkxNzcxfQ.0jg-lb4XdB7aI1o7IS9xiRUWmvMirovT5hSR_qMbTcY

{
    "title": "uusiobl",
    "author": "joku toinen",
    "url": "salainen",
    "votes": 0,
    "user": "61d5747570dab67a12981a7c"
}